[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "server"

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }

axum = "0.7.3"
hyper = "1.1.0"
tower = { version = "0.4.13", features = []}
tower-http = { version = "0.5.0", features = ["trace", "timeout", "sensitive-headers", "request-id", "cors"] }

sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio-rustls", "macros", "migrate", "chrono", "json", "uuid"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }

reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.102"
uuid = { version = "1.4.0", features = ["v4", "serde"] }

dotenv = "0.15.0"
thiserror = "1.0.43"
anyhow = "1.0.71"
