[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "server_handler"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = "0.14"
tower-http = { version = "0.4", features = ["trace", "timeout", "sensitive-headers", "request-id"] }
tower = { version = "0.4", features = []}
axum = "0.6"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "macros", "migrate", "chrono", "uuid"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.4", features = ["v4"] }


dotenv = "0.15"
thiserror = "1.0.43"
anyhow = "1.0"
