esphome:
  name: daily-update-iot
  friendly_name: daily-update-iot.itpcc.net
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

spi:
  clk_pin: GPIO14
  # miso_pin: GPIO12
  mosi_pin: GPIO13

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "daily-update-iot.itpcc.net Fallback Hotspot"
    password: !secret wifi_ap_password
  on_connect:
    - component.update: epaper_daily_update

globals:
  - id: epaper_update_countdown
    type: int
    restore_value: no
    initial_value: '0'
  - id: epaper_load
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: clk_txt
    type: std::string
    restore_value: no
    initial_value: '"INIT"'
  - id: clk_txt_countdown
    type: int
    restore_value: no
    initial_value: '0'

http_request:

online_image:
  - id: epaper_daily_update
    url: !secret epaper_url
    format: BMP
    type: RGB565
    use_transparency: false
    update_interval: 5min
    on_download_finished:
      then:
        - globals.set:
            id: epaper_load
            value: 'true'

script:
  - id: update_epaper
    then:
      - component.update: epaper

interval:
  - interval: 10s
    then:
      - lambda: |-
          if (! id(epaper_load)) {
            id(clk_txt) = "L IM";
            id(clk_txt_countdown) = 20;
          } else {
            if (id(epaper_update_countdown) == 0) {
              id(update_epaper).execute();
              id(epaper_update_countdown) = 60 * 60 / 10;
            } else {
              --id(epaper_update_countdown);
            }
          }

#Display Setup
display:
  - platform: waveshare_epaper
    cs_pin: GPIO27
    dc_pin: GPIO26
    busy_pin:
      number: GPIO25
      inverted: true
    reset_pin: GPIO33
    reset_duration: 2ms
    model: 4.20in-bv2-bwr
    id: epaper
    update_interval: 1h
    lambda: |-
      auto const white = Color(255, 255, 255);
      it.fill(white);

      id(clk_txt) = "D EP";
      id(clk_txt_countdown) = 15;

      if (! id(epaper_load)) {
        it.filled_rectangle(                 0, 0, it.get_width() / 2, it.get_height(), COLOR_ON);
        it.filled_rectangle(it.get_width() / 2, 0, it.get_width() / 2, it.get_height(), COLOR_OFF);
      } else {
        it.image(0, 0, id(epaper_daily_update));
      }
  - platform: tm1637
    clk_pin: GPIO23
    dio_pin: GPIO22
    id: clock_disp
    update_interval: 200ms
    intensity: 4
    lambda: |-
      auto time = id(ha_time).now();

      if (id(clk_txt_countdown) > 0) {
        it.print(id(clk_txt).c_str());
        --id(clk_txt_countdown);
      } else if (time.second % 2) {
        it.printf(0, "%02d.%02d", time.hour, time.minute);
      } else {
        it.printf(0, "%02d%02d", time.hour, time.minute);
      }
